### PR TITLE
First Implementations

### PR DESCRIPTION
**Pull request by iamdejan**
Here's my first implementations. These are things I've done:
1. Change configuration for API route & add simple route.
2. Add GenericResponse class.
3. Add assertion utility, so we can validate data at certain phase before being continued.
4. Add UserController, for controlling login & registration process. However, login & registration process aren't created yet.

Here's the use case for data server:
use-case-data-server

Here's the data model:
erd

### CODE REVIEW

**Comment by nieltg** [comment]
Matches are handled on match-server. You don't have to store everything. Or, you want a full history?

My suggestion: just add an interface so match-server can update each user's fastest time.

**Comment by iamdejan** [comment]
What do I need to store?

**Comment by nieltg** [comment]
> What do I need to store?

I've seen that we can only see high scores on the game, right? We can't see matches history, right?
Just keep the **users** entity if you want it.

Just give an interface to put the user's new score. If it's more than the high score, update the high score.

**Comment by iamdejan** [comment]
> > What do I need to store?
> 
> I've seen that we can only see high scores on the game, right? We can't see matches history, right?
> Just keep the **users** entity if you want it.
> 
> Just give an interface to put the user's new score. If it's more than the high score, update the high score.

I think we can show full history. I just need to put index to the timestamps column.

**Comment by nieltg** [comment]
Well, okay. Please provide an endpoint for the match server to deliver the information to you.

**Pull request merged**
